name: Д0бр0 п0ж4л0в4ть в киBEERд0м
description: |
  Всем привет и добро пожаловать на ваш (возможно) первый CTF!

  Мы рады видеть новых людей, но надо бы вас ввести в курс дела...

  Кратко: нужно показать ваши технические навыки в решении тасков - задач, посвященной определенной теме: Web, Reverse, Crypto, Forensic, Misc. Это не все существующие категории, но мы решили ограничить набор, так как некоторые категории и таски не для новичков. И еще - большая часть тасков на нашей CTF взята из реальной практики. 

  Для доказательства решения таска вам нужно сдать в систему флаг. Сдать ее можно в верхнем правом углу. А сам флаг имеет формат `ptctf{...}`, где между фигурных скобок может быть любая строка. 
  Например:
  
  ```
  ptctf{this_is_example_of_flag}
  ```
  
  Но этот флаг система не примет и очков вы за это не получите.
  Первую половинку настоящего флага от этого таска вы сможете найти в чатике соревнований (смотрите описание группы), вторую - в правилах соревнований (их важно прочитать!). Сдайте его и получите доступ к стартовым таскам. 
  
  Чатик: <https://t.me/standoff101ctf>

author: "@greg0r0"
category: sanity check
flag: ptctf{w3lc0m3_t0_cyB33Rh0us3}
warmup: true
server_port: null
